/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"

float *
ques1_1_svc(ques1 *argp, struct svc_req *rqstp)
{
	static float result;

	int i, sum = 0;

	for (i = 0; i < argp->n; i++){
		sum += argp->Y.Y_val[i];
	}

	result = (float)sum / argp->n;
	printf("Average = %f\n", result);

	return &result;
}

return2 *
ques2_2_svc(ques2 *argp, struct svc_req *rqstp)
{
	static return2  result;

	int i;
	int min = argp->Y.Y_val[0];
	int max = argp->Y.Y_val[0];

	for (i = 1; i < argp->n; i++){
		if (argp->Y.Y_val[i] < min){
			min = argp->Y.Y_val[i];
		}
		if (argp->Y.Y_val[i] > max){
			max = argp->Y.Y_val[i];
		}
	}

	printf("Min = %d\n", min);
	printf("Max = %d\n", max);

	result.Arr1[0] = min;
	result.Arr1[1] = max;

	return &result;
}

return3 *
ques3_3_svc(ques3 *argp, struct svc_req *rqstp)
{
	static return3  result;

	int i;

	result.Arr2.Arr2_len = argp->n;
	result.Arr2.Arr2_val = (float *)malloc(result.Arr2.Arr2_len*sizeof(float));

	for (i = 0; i < result.Arr2.Arr2_len; i++){
		result.Arr2.Arr2_val[i] = argp->a * argp->Y.Y_val[i];
		printf("a*Y[%d] = %f\n", i + 1, result.Arr2.Arr2_val[i]);
	}

	return &result;
}
